name: First Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: |
        echo "Hello Pavithra!"
        echo "Welcome to learn Github Actions"
    - name: Print goodbye
      run: echo "Done - bye!"
